/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE seekerBaseService PLEASE EDIT ../seeker.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Seeker } from '../../domain/uberlist_db/seeker';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Seeker.service.ts
 */

/*
 * SCHEMA DB Seeker
 *
	{
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class SeekerBaseService {

    contextUrl: string = environment.endpoint + '/seeker';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * SeekerService.create
    *   @description CRUD ACTION create
    *   @param Seeker obj Object to insert
    *
    */
    create(item: Seeker): Observable<Seeker> {
        return this.http
            .post<Seeker>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * SeekerService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SeekerService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id Seeker
    *   @returns Seeker
    *
    */
    get(id: string): Observable<Seeker> {
        return this.http
            .get<Seeker>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * SeekerService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Seeker[]> {
        return this.http
            .get<Seeker[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * SeekerService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id Seeker
    *   @returns Seeker
    *
    */
    update(item: Seeker): Observable<Seeker> {
        return this.http
            .post<Seeker>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
